name: Scraper ANATO

on:
  workflow_dispatch: 

jobs:
  run-scraper:
    runs-on: ubuntu-latest 

    steps:
      - name: ğŸ“¥ Descargar el cÃ³digo
        uses: actions/checkout@v4

      - name: ğŸ Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: ğŸ“¦ Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          
      - name: ğŸŒ Instalar Navegadores de Playwright
        run: |
          playwright install chromium
          playwright install-deps chromium 

      - name: ğŸš€ Ejecutar el Scraper
        run: python scraping_anato.py 

      - name: ğŸ’¾ Subir el CSV como Artefacto (Descargable)
        if: always() # Salva tu trabajo sin importar quÃ© pase
        uses: actions/upload-artifact@v4
        with:
          name: datos-expositores
          path: expositores_anato_final.csv
          retention-days: 7